import type { Metadata } from "next";
import "./globals.css";
// app/layout.tsx (or pages/_app.tsx)
import { Inter, Merienda } from "next/font/google";

// Load Inter as the default font
const inter = Inter({ subsets: ["latin"] });

// Load Merienda for specific titles (only when needed)
const merienda = Merienda({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  variable: "--font-merienda", // Optional: CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${inter.className} ${merienda.variable}`} lang="en">
      <body>{children}</body>
    </html>
  );
}
